packages:
  - docs
  - demo
  - package
catalog:
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  typescript: ^5.9.3
  react: ^19.1.4
  react-dom: ^19.1.4
onlyBuiltDependencies:
  - esbuild
  - sharp
