packages:
  - docs
  - demo
  - package
catalog:
  '@types/react': ^19.1.3
  '@types/react-dom': ^19.1.3
  typescript: ^5.8.3
  react: ^19.1.0
  react-dom: ^19.1.0
onlyBuiltDependencies:
  - esbuild
  - sharp
