name: Setup CI
description: Setup CI

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
