name: Version Packages

on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

jobs:
  version:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Version Commit
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm version
          commit: 'chore(release): version packages'
          publish: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
