name: Version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - uses: ./.github/actions/ci-setup

      - name: Create Version PR
        uses: changesets/action@v1
        with:
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
